// GENERATED by scripts/vendor-kernel.sh from kernel/src/clvalue.ts.
// Edit the kernel copy and re-run the script; do not edit this file.
/**
 * CLValue byte primitives shared by every Odra state decoder.
 *
 * Casper stores contract state as CLValue-serialized bytes with no schema
 * attached, so a decoder is only trustworthy if it consumes exactly as many
 * bytes as the value contains. `CLReader` therefore throws on truncation and
 * exposes `consumed`/`length` so callers can assert full consumption. A decoder
 * that silently stops early returns a plausible-looking wrong answer, which is
 * far more dangerous than an error.
 */
import { blake2b } from "@noble/hashes/blake2b";

export function u32be(n: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, n, false);
  return out;
}

export function u32le(n: number): Uint8Array {
  const out = new Uint8Array(4);
  new DataView(out.buffer).setUint32(0, n, true);
  return out;
}

export function u64le(n: bigint): Uint8Array {
  const out = new Uint8Array(8);
  new DataView(out.buffer).setBigUint64(0, n, true);
  return out;
}

export function concat(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let at = 0;
  for (const p of parts) {
    out.set(p, at);
    at += p.length;
  }
  return out;
}

export function toHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

export function fromHex(hex: string): Uint8Array {
  const clean = hex.trim();
  if (clean.length % 2 !== 0 || /[^0-9a-fA-F]/.test(clean)) {
    throw new Error(`not valid hex: ${hex.slice(0, 32)}`);
  }
  return Uint8Array.from(clean.match(/../g)?.map((h) => parseInt(h, 16)) ?? []);
}

/** Casper's key-algorithm tags, used when deriving an account hash. */
const KEY_ALGORITHM: Record<string, string> = {
  "01": "ed25519",
  "02": "secp256k1",
};

/**
 * Derives an account hash from a Casper public key.
 *
 * `blake2b256("<algorithm>" ++ 0x00 ++ key_bytes)`. Verified against three
 * independent deployed contracts whose stored owner matches the deployer public
 * key recorded in each project's environment.
 */
export function accountHashFromPublicKey(publicKeyHex: string): string {
  const hex = publicKeyHex.trim().replace(/^0x/, "");
  const algorithm = KEY_ALGORITHM[hex.slice(0, 2)];
  if (!algorithm) {
    throw new Error(
      `unknown Casper key algorithm tag "${hex.slice(0, 2)}"; expected 01 (ed25519) or 02 (secp256k1)`
    );
  }
  const expected = hex.slice(0, 2) === "01" ? 66 : 68;
  if (hex.length !== expected || /[^0-9a-fA-F]/.test(hex)) {
    throw new Error(
      `public key ${hex.slice(0, 12)}... is ${hex.length} hex chars, expected ${expected}`
    );
  }
  const name = new TextEncoder().encode(algorithm);
  const key = fromHex(hex.slice(2));
  const buf = concat(name, new Uint8Array([0]), key);
  return toHex(blake2b(buf, { dkLen: 32 }));
}

/**
 * Normalizes any address form the callers use into a bare 32-byte account hash.
 *
 * Accepts `account-hash-<64 hex>`, a bare 64-hex account hash, or a public key
 * (`01...`/`02...`) which is derived. Rejects anything else rather than
 * guessing, because a mis-derived address silently reads the wrong policy.
 */
export function toAccountHash(address: string): string {
  const raw = address.trim().replace(/^account-hash-/, "");
  if (/^(01[0-9a-fA-F]{64}|02[0-9a-fA-F]{66})$/.test(raw)) {
    return accountHashFromPublicKey(raw);
  }
  if (/^[0-9a-fA-F]{64}$/.test(raw)) return raw.toLowerCase();
  throw new Error(
    `"${address}" is neither an account hash nor a Casper public key`
  );
}

/** `Key::Account` serialization: tag 0x00 followed by the 32-byte hash. */
export function accountKeyBytes(address: string): Uint8Array {
  const hash = toAccountHash(address);
  return concat(new Uint8Array([0x00]), fromHex(hash));
}

/** Cursor over CLValue bytes. Throws rather than silently truncating. */
export class CLReader {
  private at = 0;
  constructor(private readonly buf: Uint8Array) {}

  private take(n: number): Uint8Array {
    if (this.at + n > this.buf.length) {
      throw new Error(
        `truncated CLValue: wanted ${n} bytes at ${this.at}, have ${this.buf.length}`
      );
    }
    const slice = this.buf.slice(this.at, this.at + n);
    this.at += n;
    return slice;
  }

  u8(): number {
    return this.take(1)[0];
  }

  u32le(): number {
    const b = this.take(4);
    return new DataView(b.buffer, b.byteOffset, 4).getUint32(0, true);
  }

  u64le(): bigint {
    const b = this.take(8);
    return new DataView(b.buffer, b.byteOffset, 8).getBigUint64(0, true);
  }

  /** U512 is a length byte followed by that many little-endian bytes. */
  u512(): bigint {
    const len = this.u8();
    const b = this.take(len);
    let n = 0n;
    for (let i = len - 1; i >= 0; i--) n = (n << 8n) | BigInt(b[i]);
    return n;
  }

  /** A `Key`: 1-byte tag then a 32-byte hash for accounts and contracts. */
  key(): { tag: number; hash: string } {
    const tag = this.u8();
    return { tag, hash: toHex(this.take(32)) };
  }

  /** An Odra `Address` reads as a `Key`; rendered in account-hash form. */
  address(): string {
    return `account-hash-${this.key().hash}`;
  }

  string(): string {
    const len = this.u32le();
    return new TextDecoder().decode(this.take(len));
  }

  bool(): boolean {
    return this.u8() !== 0;
  }

  /** `Option<T>`: 0x00 for None, 0x01 followed by the value for Some. */
  option<T>(read: (r: CLReader) => T): T | null {
    return this.u8() === 0 ? null : read(this);
  }

  get consumed(): number {
    return this.at;
  }

  get length(): number {
    return this.buf.length;
  }

  /**
   * Asserts the decoder consumed the whole value.
   *
   * A field-count or ordering drift in the contract shows up here as a loud
   * failure instead of as a believable but wrong decode.
   */
  assertFullyConsumed(what: string): void {
    if (this.at !== this.buf.length) {
      throw new Error(
        `${what} decode consumed ${this.at} of ${this.buf.length} bytes; the contract layout may have changed`
      );
    }
  }
}

/**
 * Strips the outer `List<U8>` length prefix that Odra wraps stored values in
 * and returns a reader over the inner bytes.
 */
export function innerBytes(hex: string): CLReader {
  const bytes = fromHex(hex);
  if (bytes.length < 4) {
    throw new Error(`stored value too short to hold a length prefix: ${hex}`);
  }
  const declared = new DataView(
    bytes.buffer,
    bytes.byteOffset,
    4
  ).getUint32(0, true);
  const inner = bytes.slice(4);
  if (inner.length !== declared) {
    throw new Error(
      `stored value length mismatch: header says ${declared}, got ${inner.length}`
    );
  }
  return new CLReader(inner);
}

/**
 * Derives the `state` dictionary item key for one Odra field.
 *
 *     dictionary_item_key = hex( blake2b256( index_bytes ++ mapping_data ) )
 *
 * `index_bytes` is the field's 1-based declaration index as a big-endian u32
 * (Odra's "legacy" packing, valid while every path index is <= 15) and
 * `mapping_data` is the CLValue serialization of the mapping key.
 */
export function dictionaryItemKey(
  fieldIndex: number,
  mappingData: Uint8Array = new Uint8Array()
): string {
  return toHex(blake2b(concat(u32be(fieldIndex), mappingData), { dkLen: 32 }));
}
