// GENERATED by scripts/vendor-kernel.sh from kernel/src/odra-state.ts.
// Edit the kernel copy and re-run the script; do not edit this file.
/**
 * A generic reader for Odra contract state over Casper JSON-RPC.
 *
 * Odra packs every module field into a single `state` dictionary keyed by a
 * hash of the field's declaration index and the mapping key, so there is no
 * entrypoint-free way to read state without reproducing that derivation. This
 * class does the RPC plumbing and key derivation; each project supplies a
 * decoder for its own structs.
 *
 * The critical safety property: an absent dictionary key is reported as `null`
 * ("no such record"), while every other failure throws. A node outage must
 * never be mistaken for "this agent has no limit". Callers that treat a missing
 * policy as permission are wrong regardless, but this class refuses to make
 * that mistake easy.
 */
import { CLReader, dictionaryItemKey, innerBytes } from "./clvalue.js";

export interface OdraNodeConfig {
  rpcUrl: string;
  /** CSPR.cloud access key. The public testnet RPC requires it. */
  accessKey?: string;
  /** Contract package hash or contract hash, with or without a prefix. */
  contractHash: string;
}

function bare(hash: string): string {
  return hash.trim().replace(/^(hash-|contract-|contract-package-)/, "");
}

export class OdraStateClient {
  private seedUref: string | null = null;
  private mainPurse: string | null | undefined;

  constructor(readonly cfg: OdraNodeConfig) {
    if (!cfg.rpcUrl) throw new Error("OdraStateClient requires an rpcUrl");
    if (!cfg.contractHash) {
      throw new Error("OdraStateClient requires a contractHash");
    }
  }

  /**
   * POSTs to the node, retrying only on 429 and 5xx.
   *
   * A shared public RPC rate-limits under load, and a single 429 is not a
   * reason for an agent to conclude it cannot verify a policy: that is a
   * transient answer being read as a permanent one. Retries are bounded and
   * backoff is exponential, so a node that is genuinely down still surfaces as
   * an error rather than hanging the request.
   *
   * 4xx other than 429 is not retried. A malformed request does not become
   * well-formed by being sent again.
   */
  private async fetchWithRetry(
    method: string,
    params: unknown,
    attempts = 4
  ): Promise<Response> {
    let lastError: Error | null = null;

    for (let attempt = 0; attempt < attempts; attempt++) {
      if (attempt > 0) {
        // 250ms, 500ms, 1s. Short enough to stay inside a request, long enough
        // to clear a per-second limiter.
        await new Promise((r) => setTimeout(r, 250 * 2 ** (attempt - 1)));
      }
      try {
        const res = await fetch(this.cfg.rpcUrl, {
          method: "POST",
          headers: {
            "content-type": "application/json",
            ...(this.cfg.accessKey ? { authorization: this.cfg.accessKey } : {}),
          },
          body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params }),
        });
        if (res.status === 429 || res.status >= 500) {
          lastError = new Error(`node returned HTTP ${res.status} for ${method}`);
          continue;
        }
        return res;
      } catch (err) {
        lastError = new Error(
          `cannot reach Casper node at ${this.cfg.rpcUrl}: ${
            err instanceof Error ? err.message : String(err)
          }`
        );
      }
    }

    throw lastError ?? new Error(`${method} failed for an unknown reason`);
  }

  async rpc<T>(method: string, params: unknown): Promise<T> {
    const res = await this.fetchWithRetry(method, params);
    if (!res.ok) {
      throw new Error(`node returned HTTP ${res.status} for ${method}`);
    }
    const json = (await res.json()) as {
      result?: T;
      error?: { message: string; data?: string };
    };
    if (json.error) {
      throw new Error(
        `${method} failed: ${json.error.message}${
          json.error.data ? ` (${json.error.data})` : ""
        }`
      );
    }
    if (json.result === undefined) {
      throw new Error(`${method} returned no result`);
    }
    return json.result;
  }

  async stateRootHash(): Promise<string> {
    const r = await this.rpc<{ state_root_hash: string }>(
      "chain_get_state_root_hash",
      null
    );
    return r.state_root_hash;
  }

  /** Current node block time in ms. Used to evaluate expiry clauses. */
  async blockTimeMs(): Promise<number> {
    const r = await this.rpc<{
      block_with_signatures: {
        block: { Version2: { header: { timestamp: string } } };
      };
    }>("chain_get_block", null);
    return new Date(
      r.block_with_signatures.block.Version2.header.timestamp
    ).getTime();
  }

  /** Resolves the concrete contract hash, following a package if needed. */
  private async namedKeys(): Promise<Array<{ name: string; key: string }>> {
    const r = await this.rpc<{
      stored_value: {
        Contract?: { named_keys: Array<{ name: string; key: string }> };
        ContractPackage?: {
          versions: Array<{ contract_version: number; contract_hash: string }>;
        };
      };
    }>("query_global_state", {
      key: `hash-${bare(this.cfg.contractHash)}`,
      path: [],
    });

    if (r.stored_value.Contract) return r.stored_value.Contract.named_keys;

    const pkg = r.stored_value.ContractPackage;
    if (!pkg || pkg.versions.length === 0) {
      throw new Error(
        `hash-${bare(this.cfg.contractHash)} is neither a contract nor a package with versions`
      );
    }
    // Newest enabled version. Odra deploys append, so the last entry is live.
    const latest = pkg.versions.reduce((a, b) =>
      b.contract_version > a.contract_version ? b : a
    );
    // The package lists versions as `contract-<hash>`, but query_global_state
    // only accepts the `hash-` prefix, so the prefix has to be normalized.
    const inner = await this.rpc<{
      stored_value: { Contract: { named_keys: Array<{ name: string; key: string }> } };
    }>("query_global_state", {
      key: `hash-${bare(latest.contract_hash)}`,
      path: [],
    });
    return inner.stored_value.Contract.named_keys;
  }

  /** Resolves and caches the contract's `state` dictionary seed URef. */
  private async stateSeedUref(): Promise<string> {
    if (this.seedUref) return this.seedUref;
    const keys = await this.namedKeys();
    const found = keys.find((k) => k.name === "state");
    if (!found) {
      throw new Error(
        "contract has no `state` named key; it may not be an Odra contract"
      );
    }
    this.seedUref = found.key;
    return found.key;
  }

  /** The contract's own purse, when the module holds native tokens. */
  async contractPurseUref(): Promise<string | null> {
    if (this.mainPurse !== undefined) return this.mainPurse;
    const keys = await this.namedKeys();
    this.mainPurse =
      keys.find((k) => k.name === "__contract_main_purse")?.key ?? null;
    return this.mainPurse;
  }

  /**
   * The contract's native token balance in motes, or null when the module
   * holds no purse. This is the value `self_balance()` checks on-chain.
   */
  async contractBalanceMotes(): Promise<string | null> {
    const purse = await this.contractPurseUref();
    if (!purse) return null;
    const r = await this.rpc<{ balance: string }>("query_balance", {
      purse_identifier: { purse_uref: purse },
    });
    return r.balance;
  }

  /** Raw CLValue hex for one dictionary item, or null when the key is absent. */
  async readRaw(itemKey: string): Promise<string | null> {
    const [srh, seed] = await Promise.all([
      this.stateRootHash(),
      this.stateSeedUref(),
    ]);
    try {
      const r = await this.rpc<{ stored_value: { CLValue: { bytes: string } } }>(
        "state_get_dictionary_item",
        {
          state_root_hash: srh,
          dictionary_identifier: {
            URef: { seed_uref: seed, dictionary_item_key: itemKey },
          },
        }
      );
      return r.stored_value.CLValue.bytes;
    } catch (err) {
      // An absent key is a legitimate "no record". Every other error must
      // propagate so an outage is never read as an unrestricted agent.
      if (
        err instanceof Error &&
        /(value was not found|not found in|dictionary key not found)/i.test(
          err.message
        )
      ) {
        return null;
      }
      throw err;
    }
  }

  /**
   * Reads one Odra field and decodes it, or returns null when unset.
   *
   * `what` names the field in error messages so a layout drift is traceable to
   * a specific struct rather than to "some decode failed".
   */
  async readField<T>(
    fieldIndex: number,
    mappingData: Uint8Array | undefined,
    what: string,
    decode: (r: CLReader) => T
  ): Promise<T | null> {
    const hex = await this.readRaw(dictionaryItemKey(fieldIndex, mappingData));
    if (hex === null) return null;
    const reader = innerBytes(hex);
    const value = decode(reader);
    reader.assertFullyConsumed(what);
    return value;
  }
}
