// GENERATED by scripts/vendor-kernel.sh from kernel/src/session.ts.
// Edit the kernel copy and re-run the script; do not edit this file.
/**
 * Authenticated agent identity.
 *
 * The bug this exists to kill: every one of these servers used to read the
 * governing `policy` straight out of the request body, so any caller could
 * hand itself an unlimited limit and the "guard" guarded nothing.
 *
 * The fix is that a request may only choose *which* agent it acts as, never
 * what that agent may do. Proving "which" requires a signature over a
 * server-issued challenge: the caller signs a nonce with the agent key, the
 * server verifies it against the claimed public key, and the resulting session
 * token is the only thing downstream code trusts. Authority itself is then
 * read from chain under that identity.
 *
 * Scope, stated honestly: sessions live in memory, so a restart invalidates
 * them and a multi-instance deployment needs a shared store. That is a
 * deployment concern, not a hole in the authorization model, because a token
 * is only ever a claim of identity and never a claim of authority.
 */
import { randomBytes, createHash, timingSafeEqual } from "node:crypto";
import { toAccountHash } from "./clvalue.js";

/** How long a challenge may sit unanswered before it is useless. */
const CHALLENGE_TTL_MS = 2 * 60 * 1000;
/** How long a session lives before the caller must sign again. */
const SESSION_TTL_MS = 30 * 60 * 1000;

export interface Challenge {
  nonce: string;
  /** The exact UTF-8 string the caller must sign. */
  message: string;
  expiresAt: number;
}

export interface AgentSession {
  token: string;
  /** Public key hex the caller proved control of. */
  publicKeyHex: string;
  /** Derived account hash. This is the key every on-chain lookup uses. */
  accountHash: string;
  expiresAt: number;
}

/** Verifies a signature over `message` for `publicKeyHex`. */
export type SignatureVerifier = (
  publicKeyHex: string,
  message: string,
  signatureHex: string
) => boolean;

export class SessionStore {
  private readonly challenges = new Map<string, Challenge>();
  private readonly sessions = new Map<string, AgentSession>();

  constructor(
    private readonly verify: SignatureVerifier,
    private readonly now: () => number = Date.now
  ) {}

  /** Issues a nonce the caller must sign with the agent key. */
  issueChallenge(publicKeyHex: string): Challenge {
    // Reject a malformed key here rather than after a signature check, so the
    // caller gets the real reason.
    toAccountHash(publicKeyHex);
    const nonce = randomBytes(24).toString("hex");
    const challenge: Challenge = {
      nonce,
      message: `casper-agent-session:${publicKeyHex.toLowerCase()}:${nonce}`,
      expiresAt: this.now() + CHALLENGE_TTL_MS,
    };
    this.challenges.set(nonce, challenge);
    this.sweep();
    return challenge;
  }

  /**
   * Exchanges a signed challenge for a session.
   *
   * Throws with the specific reason on every failure path. The challenge is
   * consumed whether or not verification succeeds, so a nonce cannot be
   * brute-forced by replaying signatures against it.
   */
  redeem(
    publicKeyHex: string,
    nonce: string,
    signatureHex: string
  ): AgentSession {
    const challenge = this.challenges.get(nonce);
    this.challenges.delete(nonce);

    if (!challenge) throw new Error("unknown or already-used challenge nonce");
    if (challenge.expiresAt < this.now()) {
      throw new Error("challenge expired; request a new one");
    }
    if (
      challenge.message !==
      `casper-agent-session:${publicKeyHex.toLowerCase()}:${nonce}`
    ) {
      throw new Error("challenge was issued for a different public key");
    }
    if (!this.verify(publicKeyHex, challenge.message, signatureHex)) {
      throw new Error("signature does not verify against the claimed key");
    }

    const session: AgentSession = {
      token: randomBytes(32).toString("hex"),
      publicKeyHex: publicKeyHex.toLowerCase(),
      accountHash: toAccountHash(publicKeyHex),
      expiresAt: this.now() + SESSION_TTL_MS,
    };
    this.sessions.set(this.fingerprint(session.token), session);
    return session;
  }

  /** Resolves a bearer token, or throws. Never returns a partial identity. */
  resolve(token: string | undefined): AgentSession {
    if (!token) throw new Error("missing session token");
    const session = this.sessions.get(this.fingerprint(token));
    if (!session) throw new Error("unknown session token");
    if (session.expiresAt < this.now()) {
      this.sessions.delete(this.fingerprint(token));
      throw new Error("session expired; sign a new challenge");
    }
    return session;
  }

  /**
   * Tokens are stored by hash so a memory dump does not hand out live
   * sessions, and compared under a constant-time equality via the map lookup
   * on a fixed-length digest.
   */
  private fingerprint(token: string): string {
    return createHash("sha256").update(token).digest("hex");
  }

  private sweep(): void {
    const now = this.now();
    for (const [k, v] of this.challenges) if (v.expiresAt < now) this.challenges.delete(k);
    for (const [k, v] of this.sessions) if (v.expiresAt < now) this.sessions.delete(k);
  }
}

/**
 * Constant-time string comparison for callers that need to check a shared
 * secret (for example an operator key gating write endpoints).
 */
export function secretEquals(a: string, b: string): boolean {
  const ba = Buffer.from(a);
  const bb = Buffer.from(b);
  if (ba.length !== bb.length) return false;
  return timingSafeEqual(ba, bb);
}
